all:
  children:

    tfe:
      hosts:
        tfe01:
          ansible_host: "{{ lookup('env', 'VM1_ANSIBLE_HOST') }}"
          ansible_user: "{{ lookup('env', 'VM1_ANSIBLE_USER') }}"
          ansible_password: "{{ lookup('env', 'VM1_ANSIBLE_PASSWORD') }}"

        # tfe02 — uncomment when second active-active node is ready
        # tfe02:
        #   ansible_host: "{{ lookup('env', 'VM2_ANSIBLE_HOST') }}"
        #   ansible_user: "{{ lookup('env', 'VM2_ANSIBLE_USER') }}"
        #   ansible_password: "{{ lookup('env', 'VM2_ANSIBLE_PASSWORD') }}"

    services:
      hosts:
        services01:
          ansible_host: "{{ lookup('env', 'SERVICE_ANSIBLE_HOST') }}"
          ansible_user: "{{ lookup('env', 'SERVICE_ANSIBLE_USER') }}"
          ansible_password: "{{ lookup('env', 'SERVICE_ANSIBLE_PASSWORD') }}"